ansible-galaxy コマンドのローカル化とその他のユーティリティ周りに機能追加.
link-u/ansible-tools_client pull request #5
Opened 2020-10-26 14:22 UTC by y-hashida

## 変更点

* `_scripts/wrapper.sh` コマンドに以下の機能を追加.
  * `wrapper.sh` そのもの (リンク経由ではなく) を実行した場合 ansible のインストールのみをする.
  * ↑の機能を使って, ansible をインストールする install_ansible.sh を用意.
    (このスクリプト内に ansible-galaxy コマンドを使って追加のモジュールをインストールなどできるように改変したい.)
  * _venvs/ 以下をクリーンにする clean_venvs.sh を用意
  * 環境変数 `ANSIBLE_COLLECTIONS_PATHS` の用意. またその先頭に `${VENV_DIR}/share/ansible/collections` を追加
    (ansible-galaxy でインストールする collections のローカル化のため.
  * デフォルトの req.txt を以下のように変更
    * ansible から ansible-base に変更. バージョンは 2.10系に更新.
    * Jinja2 のバージョンを 2.11系に更新.

<br>

## ansible-galaxy の使い方例

### community.general のインストール

[community.general の HP](https://galaxy.ansible.com/community/general)

```
./ansible-galaxy collection install community.general
```

### community.zabbix のインストール

[community.zabbix の HP](https://galaxy.ansible.com/community/zabbix)

```
./ansible-galaxy collection install community.zabbix
```

<br>

## 参考

* https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths
* https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-collection-from-galaxy

2020-10-28 08:35 UTC, ledyba-z requested changes
コメントで誤解を生んでしまったぽいので解消していただければ…というのと、
-pを更に指定する必要あるのかちょっと気になったので質問です

2020-10-28 08:35 UTC, ledyba-z commented on _scripts/wrapper.sh
> +## busybox のコマンド名とコマンドライン引数を取得
これを「busybox」と呼んでるわけじゃなくて、[busybox](https://ja.wikipedia.org/wiki/BusyBox)っていう組み込みLinux向けのコマンドラインツール群（lsとかcatとか）の方法を真似してるって意味でした（わかりづらくてすまん）

busyboxだとlsもcatも全部同じ`busybox`っていう実行ファイルへのシンボリックリンクになってて、$0がlsかrmかcatなのかで実際に実行する処理を分けてるんですな

参考：
https://www.hiroom2.com/2014/02/21/busybox%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9/

// コマンドごとに別々の実行ファイルに分ける時よりファイルサイズの消費量が少なくて、
// 容量に対する制限が厳しい組み込み環境では嬉しい…らしい。

だからここは「wrapperのコマンド名とコマンドライン引数を取得」とかかな。

2020-10-28 08:35 UTC, ledyba-z commented on _scripts/wrapper.sh
> +            ARGS+=("-p" "${VENV_COLLECTIONS_PATH}")
-pで何も指定してない時は

> If you don’t specify a path, ansible-galaxy collection install installs the collection to the first path defined in COLLECTIONS_PATHS, which by default is ~/.ansible/collections
> [Galaxy User Guide — Ansible Documentation](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-collection-from-galaxy)

が効くから上でexportした`ANSIBLE_COLLECTIONS_PATHS="${VENV_COLLECTIONS_PATH}:${DEFAULT_COLLECTIONS_PATHS}"`で十分かなと思ったんだけど、足りないのん？

2020-10-28 09:04 UTC, y-hashida commented on _scripts/wrapper.sh
> +            ARGS+=("-p" "${VENV_COLLECTIONS_PATH}")
確かに, `ANSIBLE_COLLECTIONS_PATHS="${VENV_COLLECTIONS_PATH}:${DEFAULT_COLLECTIONS_PATHS}"` だけで十分でした・・・！
ANSIBLE_COLLECTIONS_PATHS の先頭にあるパスに自動でインストールされると書いてありましたね！
修正しておきます！

2020-10-28 09:05 UTC, y-hashida commented on _scripts/wrapper.sh
> +## busybox のコマンド名とコマンドライン引数を取得
なるほど！
プログラムを作る手法として「busybox」 という考え方があるのかと勘違いしてましたｗ
busybox 自体がすでに具体的なプログラムなんですね！

2020-10-29 05:23 UTC, ledyba-z commented on _scripts/wrapper.sh
> +## busybox のコマンド名とコマンドライン引数を取得
そうそう、busyboxっていうプログラムがあります。
NASとかに昔はよく入ってたｗ

2020-10-29 05:24 UTC, ledyba-z commented on _scripts/wrapper.sh
> +            ARGS+=("-p" "${VENV_COLLECTIONS_PATH}")
完璧ッス、ありがとう。

2020-10-29 05:24 UTC, ledyba-z approved these changes
修正ありがとう、LGTM。

2020-10-29 05:24 UTC, merged